name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: docker compose up --detach --build
      - timeout-minutes: 1
        run: |
          until docker compose exec pocketbase wget --no-verbose --tries=1 --spider http://localhost:8090/api/health; do
            sleep 5
          done
