name: Update PocketBase Version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - run: |
          git config --global user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - id: latest
        name: Get latest PocketBase version
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          tag_name="$(gh release view -R pocketbase/pocketbase --json tagName --jq '.tagName')"
          if [ -z "$tag_name" ]; then
            echo "Error: tag_name is empty"
            exit 1
          fi
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT

      - name: Update Dockerfile.pocketbase with latest PocketBase version
        run: |
          latest_version=$(echo "${{ steps.latest.outputs.tag_name }}" | sed 's/^v//')
          sed -i "s/^ARG PB_VERSION=.*/ARG PB_VERSION=${latest_version}/" Dockerfile.pocketbase

      - id: cpr
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update-pocketbase-version
          commit-message: "chore(deps): Update PocketBase version to ${{ steps.latest.outputs.tag_name }}"
          title: "chore(deps): Update PocketBase version to ${{ steps.latest.outputs.tag_name }}"
          body: |
            Update PocketBase version to ${{ steps.latest.outputs.tag_name }}.

      - name: Enable Pull Request Automerge
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
